blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image = models.ImageField(
        upload_to='images')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment, Category
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)


class PostSearchForm(forms.Form):
    q = forms.CharField()
    c = forms.ModelChoiceField(
        queryset=Category.objects.all().order_by('name'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['c'].label = ''
        self.fields['c'].required = False
        self.fields['c'].label = 'Category'
        self.fields['q'].label = 'Search For'
        self.fields['q'].widget.attrs.update(
            {'class': 'form-control'})

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment, Category
from .forms import NewCommentForm, PostSearchForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


def home(request):

    all_posts = Post.newmanager.all()

    return render(request, 'index.html', {'posts': all_posts})


def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments, })


class CatListView(ListView):
    template_name = 'category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list = Category.objects.exclude(name='default')
    context = {
        "category_list": category_list,
    }
    return context


def post_search(request):
    form = PostSearchForm()
    q = ''
    c = ''
    results = []
    query = Q()

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']

            if c is not None:
                query &= Q(category=c)
            if q is not None:
                query &= Q(title__contains=q)

            results = Post.objects.filter(query)

    return render(request, 'search.html',
                  {'form': form,
                   'q': q,
                   'results': results})

blog/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>{% block title %} Welcome to blog {% endblock %}</title>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/search">Search</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in category_list %}
            <a class="dropdown-item" href="/category/{{ category.name}}">
              {{ category.name|title }}
            </a>
            {% endfor %}
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="/search/" method="get">
        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>

blog/templates/category.html
    {% extends "base.html" %}

    {% block title %}
    Catlist
    {% endblock %}

    {% block content %}

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-12 pb-5">
            <h1> List of {{catlist.cat}} posts</h1>
          </div>
          {% for post in catlist.posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    {% endblock %}

blog/templates/index.html
    {% extends "base.html" %}

    {% block title %}
    Welcome to Blog
    {% endblock %}

    {% block content %}
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% for post in posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                <div class="card-body">
                  <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                  <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endblock %}

blog/templates/search.html
{% extends "base.html" %}
{% block title %}Search Page{% endblock %}
{% block content %}
<div class="container pt-5">

    {% if q %}
    <h1>Posts containing "{{ q }}"

        {% if c %}
        In category "{{ c }}"
        {% endif %}

    </h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in results %}
                <div class="col-md-4">
                    <a class="text-dark" href="{{post.get_absolute_url}}">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                                <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <p>There are no results for your query.</p>
                {% endfor %}
            </div>
        </div>
    </div>


    <p><a href="{% url "blog:post_search" %}" class="btn btn-primary" role="button" aria-disabled="true">New
            Search</a>
    </p>
    {% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input class="btn btn-primary my-1" type="submit" value="Search">
    </form>
    {% endif %}

</div>
{% endblock %}

blog/templates/single.html
{% extends "base.html" %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <h1>{{post.title}}</h1>
    </div>
    <div class="col-md-9"><img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}"></div>
    <div class="col-md-7">
      <p>{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2" style="border: 1px solid grey">
          <div class="d-flex justify-content-between">By {{ node.name }}<div></div>{{ node.publish }}</div>
          <div>{{ node.content }}</div>
          <hr />
          {% if node.level < 3 %}
          <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <div id="myDIV" style="display:block;">
        <form id="myForm" method="post">
          <h2>Create new comment</h2>
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}